// Embedded Ed25519 public keys that trust update manifests.
//
// Generated by `python3 tools/gen-update-keys.py` on 2026-09-04T21:47:52.596936+00:00. Do not hand edit: re-run the tool to
// rotate. Private seeds are stored as the `UPDATE_SIGNING_SK` Actions
// secret (primary) and in a password manager (standby). Verification
// tries every key below and accepts on the first success.
const Map<String, String> kUpdateVerifyKeys = <String, String>{
  '2026-09-a': 'SptdWeLs7kF04P33qFfcAQQ+ohuB3UIIXuF3r+hGmXY=',
  '2026-09-b': 'ZE1U8CbMh2PMs3WlWSrrf0mF8cJNdEu4sVYx1pngXYY=',
};
