// Signed update manifest model (`latest.json`).
//
// The manifest is generated by CI on every stable tag and signed with an
// offline Ed25519 key. The app verifies the detached signature in
// `latest.json.sig` BEFORE trusting any field below, then validates the
// schema again here (defense in depth: a valid signature over malformed
// data still means "no update").

import 'update_asset.dart';
import 'update_version.dart';

/// Validated manifest. Construct only via [UpdateRelease.tryParse].
class UpdateRelease {
  const UpdateRelease._({
    required this.tag,
    required this.version,
    required this.publishedAt,
    required this.notes,
    required this.releasePageUrl,
    required this.macos,
    required this.windows,
  });

  final String tag;
  final UpdateVersion version;
  final DateTime publishedAt;
  final String notes;
  final String releasePageUrl;
  final UpdateAsset macos;
  final UpdateAsset windows;

  static const int maxNotesLength = 2000;
  static const int minAssetBytes = 1024 * 1024;
  static const int maxAssetBytes = 1536 * 1024 * 1024;

  static final RegExp _dmgName = RegExp(r'^CrazyCut\.dmg$');
  static final RegExp _zipName = RegExp(r'^CrazyCut-Windows\.zip$');
  static final RegExp _sha256Hex = RegExp(r'^[0-9a-fA-F]{64}$');

  /// Hosts the updater will ever download from. Anything else is rejected,
  /// including on redirects (enforced by the HTTP client as well).
  static const List<String> allowedHosts = <String>[
    'api.github.com',
    'github.com',
    'objects.githubusercontent.com',
    'release-assets.githubusercontent.com',
  ];

  static bool isAllowedUrl(String raw) {
    final uri = Uri.tryParse(raw);
    if (uri == null || !uri.isAbsolute) return false;
    if (uri.scheme != 'https') return false;
    return allowedHosts.contains(uri.host.toLowerCase());
  }

  static UpdateAsset? _parseAsset(
    dynamic json,
    RegExp namePattern,
    List<String> errors,
    String key,
  ) {
    if (json is! Map<String, dynamic>) {
      errors.add('assets.$key must be an object');
      return null;
    }
    final file = json['file'];
    final url = json['url'];
    final sha256 = json['sha256'];
    final size = json['size'];
    if (file is! String || !namePattern.hasMatch(file)) {
      errors.add('assets.$key.file has an unexpected name');
      return null;
    }
    if (url is! String || !isAllowedUrl(url)) {
      errors.add('assets.$key.url is not an allowed https URL');
      return null;
    }
    if (sha256 is! String || !_sha256Hex.hasMatch(sha256)) {
      errors.add('assets.$key.sha256 must be 64 hex chars');
      return null;
    }
    if (size is! int || size < minAssetBytes || size > maxAssetBytes) {
      errors.add('assets.$key.size is out of bounds');
      return null;
    }
    return UpdateAsset(
      file: file,
      url: url,
      sha256: sha256.toLowerCase(),
      size: size,
    );
  }

  /// Returns null when the manifest is malformed or untrustworthy.
  /// [errors] collects human readable reasons for logs (never shown raw).
  static UpdateRelease? tryParse(
    Map<String, dynamic> json, {
    List<String>? errors,
  }) {
    final problems = errors ?? <String>[];
    final tag = json['tag'];
    final versionRaw = json['version'];
    if (tag is! String || !UpdateVersion.isStableTag(tag)) {
      problems.add('tag must match vX.Y.Z');
      return null;
    }
    if (versionRaw is! String) {
      problems.add('version must be a string');
      return null;
    }
    final version = UpdateVersion.tryParse(versionRaw);
    if (version == null || version.toString() != tag.substring(1)) {
      problems.add('version must equal tag without the leading v');
      return null;
    }
    DateTime? publishedAt;
    final publishedRaw = json['published_at'];
    if (publishedRaw is String) {
      try {
        publishedAt = DateTime.parse(publishedRaw);
      } on FormatException {
        problems.add('published_at is not a valid date');
        return null;
      }
      if (publishedAt.isAfter(DateTime.now().toUtc().add(
        const Duration(minutes: 10),
      ))) {
        problems.add('published_at is in the future');
        return null;
      }
    } else {
      problems.add('published_at must be a string');
      return null;
    }
    final releasePageUrl = json['release_page_url'];
    if (releasePageUrl is! String || !isAllowedUrl(releasePageUrl)) {
      problems.add('release_page_url is not an allowed https URL');
      return null;
    }
    var notes = '';
    final notesRaw = json['notes'];
    if (notesRaw is String) {
      notes =
          notesRaw.length > maxNotesLength
              ? notesRaw.substring(0, maxNotesLength)
              : notesRaw;
    }
    final assets = json['assets'];
    if (assets is! Map<String, dynamic>) {
      problems.add('assets must be an object');
      return null;
    }
    final macos = _parseAsset(assets['macos'], _dmgName, problems, 'macos');
    final windows = _parseAsset(
      assets['windows'],
      _zipName,
      problems,
      'windows',
    );
    if (macos == null || windows == null) return null;
    return UpdateRelease._(
      tag: tag,
      version: version,
      publishedAt: publishedAt,
      notes: notes,
      releasePageUrl: releasePageUrl,
      macos: macos,
      windows: windows,
    );
  }
}
