#!/usr/bin/env python3
# Generates the offline Ed25519 signing pairs for the updater.
#
# Run once from the repo root:
#   python3 tools/gen-update-keys.py
#
# What it does:
#   - Generates a primary and a standby Ed25519 keypair (PyNaCl).
#   - Rewrites app/lib/modules/updates/domain/update_keys.dart with the two
#     base64 public keys (safe to commit).
#   - Writes the two private seeds to private_keys/ (gitignored) with
#     owner-only permissions. Private seeds are NEVER printed: stdout shows
#     public keys and key IDs only.
#
# Next steps after running:
#   1. Save both seeds in a password manager.
#   2. Add the PRIMARY seed as the GitHub Actions secret UPDATE_SIGNING_SK.
#   3. Keep the standby seed offline until rotation day.
#   4. Delete the local seed file once stored, or move it to an encrypted
#      volume. Never commit it.

import base64
import datetime
import os
import stat
import sys

try:
    from nacl.signing import SigningKey
except ImportError:
    sys.exit("error: PyNaCl is required: python3 -m pip install pynacl")


def make_pair(key_id):
    signing = SigningKey.generate()
    seed_b64 = base64.b64encode(bytes(signing)).decode()
    pub_b64 = base64.b64encode(bytes(signing.verify_key)).decode()
    return {"id": key_id, "seed": seed_b64, "public": pub_b64}


def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m")
    primary_id = sys.argv[1] if len(sys.argv) > 1 else "%s-a" % stamp
    standby_id = sys.argv[2] if len(sys.argv) > 2 else "%s-b" % stamp

    primary = make_pair(primary_id)
    standby = make_pair(standby_id)

    keys_path = os.path.join(
        repo_root, "app", "lib", "modules", "updates", "domain",
        "update_keys.dart",
    )
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    with open(keys_path, "w") as f:
        f.write(
            "// Embedded Ed25519 public keys that trust update manifests.\n"
            "//\n"
            "// Generated by `python3 tools/gen-update-keys.py` on %s. "
            "Do not hand edit: re-run the tool to\n"
            "// rotate. Private seeds are stored as the `UPDATE_SIGNING_SK` "
            "Actions\n"
            "// secret (primary) and in a password manager (standby). "
            "Verification\n"
            "// tries every key below and accepts on the first success.\n"
            "const Map<String, String> kUpdateVerifyKeys = "
            "<String, String>{\n"
            "  '%s': '%s',\n"
            "  '%s': '%s',\n"
            "};\n" % (now, primary["id"], primary["public"],
                      standby["id"], standby["public"])
        )

    secrets_dir = os.path.join(repo_root, "private_keys")
    os.makedirs(secrets_dir, exist_ok=True)
    seeds_path = os.path.join(
        secrets_dir, "update-signing-seeds.%s.txt" % stamp)
    with open(seeds_path, "w") as f:
        f.write(
            "CrazyCut update signing seeds, generated %s.\n"
            "Store in a password manager, add PRIMARY to GitHub secret "
            "UPDATE_SIGNING_SK, then delete this file or move it offline.\n"
            "NEVER commit this file.\n\n"
            "PRIMARY id: %s\n"
            "PRIMARY seed (UPDATE_SIGNING_SK): %s\n\n"
            "STANDBY id: %s\n"
            "STANDBY seed (offline only): %s\n"
            % (now, primary["id"], primary["seed"],
               standby["id"], standby["seed"])
        )
    os.chmod(seeds_path, stat.S_IRUSR | stat.S_IWUSR)

    # Only public material reaches stdout.
    print("Wrote public keys to %s:" % keys_path)
    print("  %s: %s" % (primary["id"], primary["public"]))
    print("  %s: %s" % (standby["id"], standby["public"]))
    print("Wrote private seeds to %s (owner-only, gitignored)." % seeds_path)


if __name__ == "__main__":
    main()
